"""Pre-loaded filament manufacturer and product database.

Each vendor entry contains default filament lines with accurate specs
for slicer profile generation.

Color hex codes sourced from manufacturer spec sheets, Prusa Knowledge Base,
Bambu Lab official hex tables, Polymaker product pages, filamentcolors.xyz
colorimeter measurements, and official product listings.
"""

from __future__ import annotations

# Material defaults: (density, nozzle_min, nozzle_default, nozzle_max,
#                     bed_min, bed_default, bed_max, max_vol_flow, tensile_strength_mpa)
# Tensile strength values are typical ranges for FDM-printed parts (MPa).
_MAT = {
    "PLA":  (1.24, 190, 210, 230, 25, 55, 65, 15.0, 37.0),
    "PLA+": (1.24, 205, 215, 225, 45, 60, 70, 15.0, 46.0),
    "PETG": (1.27, 220, 240, 260, 65, 80, 90, 8.0, 50.0),
    "ABS":  (1.04, 220, 245, 260, 85, 100, 110, 11.0, 40.0),
    "ABS+": (1.04, 230, 245, 260, 90, 100, 110, 11.0, 43.0),
    "ASA":  (1.07, 240, 255, 270, 90, 105, 110, 11.0, 55.0),
    "TPU":  (1.21, 210, 220, 230, 25, 50, 60, 2.5, 26.0),
}


def _colors(material: str, colors: list[tuple[str, str]], **overrides) -> list[dict]:
    """Build filament entries from a color list and material defaults."""
    d, n_min, n_def, n_max, b_min, b_def, b_max, flow, tensile = _MAT.get(
        material, _MAT["PLA"]
    )
    result = []
    for color_name, color_hex in colors:
        entry = {
            "name": f"{material} {color_name}",
            "material": material,
            "color_hex": color_hex,
            "color_name": color_name,
            "diameter_mm": 1.75,
            "density_g_cm3": overrides.get("density", d),
            "net_weight_g": overrides.get("net_weight_g", 1000.0),
            "nozzle_temp_min": overrides.get("nozzle_min", n_min),
            "nozzle_temp_default": overrides.get("nozzle_default", n_def),
            "nozzle_temp_max": overrides.get("nozzle_max", n_max),
            "bed_temp_min": overrides.get("bed_min", b_min),
            "bed_temp_default": overrides.get("bed_default", b_def),
            "bed_temp_max": overrides.get("bed_max", b_max),
            "max_volumetric_flow": overrides.get("max_flow", flow),
            "max_print_speed": overrides.get("max_speed", None),
            "tensile_strength_mpa": overrides.get("tensile_strength_mpa", tensile),
            "price": overrides.get("price", None),
            "price_unit": "per_spool" if overrides.get("price") else None,
        }
        result.append(entry)
    return result


# ══════════════════════════════════════════════════════════════════════════
#  VENDOR SEED DATA
# ══════════════════════════════════════════════════════════════════════════

SEED_VENDORS: list[dict] = [

    # ── Prusament ─────────────────────────────────────────────────────
    # Hex codes from Prusa Knowledge Base HueForge tables
    {
        "name": "Prusament",
        "website": "https://prusament.com",
        "empty_spool_weight_g": 201.0,
        "filaments": [
            *_colors("PLA", [
                ("Jet Black", "#24292A"),
                ("Prusa Galaxy Black", "#3D3E3C"),
                ("Gentleman's Grey", "#354046"),
                ("Anthracite Grey", "#3F4647"),
                ("Gravity Grey", "#9FA4A7"),
                ("Galaxy Silver", "#999A9F"),
                ("Pearl Mouse", "#A49D8D"),
                ("Marble Grey", "#B0B4B4"),
                ("Pristine White", "#E6EAED"),
                ("Vanilla White", "#D9D4C4"),
                ("Natural", "#DFDFD3"),
                ("Lipstick Red", "#D03036"),
                ("Blood Red", "#990303"),
                ("Azure Blue", "#0682AC"),
                ("Chalky Blue", "#6F9AAA"),
                ("Simply Green", "#70A640"),
                ("Opal Green", "#075B49"),
                ("Galaxy Green", "#426639"),
                ("Army Green", "#5E6344"),
                ("Pistachio Green", "#93A683"),
                ("Pineapple Yellow", "#EFD006"),
                ("Prusa Orange", "#FE6E31"),
                ("Galaxy Purple", "#0F0939"),
                ("Noctua Beige", "#E7CEB4"),
                ("Noctua Brown", "#653525"),
                ("Prusa Pro Green", "#00C389"),
                ("Recycled", "#0D210C"),
                ("Premium Mystic Brown", "#482E31"),
                ("Premium Mystic Green", "#555845"),
                ("Blend Lime Green", "#A7B852"),
                ("Blend Ms. Pink", "#E34A93"),
                ("Blend My Silverness", "#AEB8C0"),
                ("Blend Oh My Gold", "#CE9F2D"),
                ("Blend Royal Blue", "#04518E"),
                ("Blend Viva La Bronze", "#B38E3E"),
                ("Blend Pearl White", "#D0D7D6"),
                ("Galaxy Red", "#8C1B18"),
            ], nozzle_min=200, nozzle_default=215, nozzle_max=230,
               bed_min=40, bed_default=60, price=29.99),
            *_colors("PLA", [
                ("rPLA Risotto Pigment", "#CCC9BF"),
                ("rPLA Algae Pigment", "#674B41"),
                ("rPLA Wine Pigment", "#5E493F"),
                ("rPLA Corn Pigment", "#B37B46"),
            ], nozzle_min=200, nozzle_default=215, nozzle_max=230,
               bed_min=40, bed_default=60, price=24.99),
            *_colors("PETG", [
                ("Jet Black", "#292B2B"),
                ("Prusa Galaxy Black", "#494546"),
                ("Matte Black", "#303635"),
                ("Signal White", "#E5E0E1"),
                ("Lipstick Red", "#BB2E32"),
                ("Ocean Blue", "#1A4C54"),
                ("Chalky Blue", "#6F9AA9"),
                ("Sky Blue", "#346CE3"),
                ("Ultramarine Blue Transparent", "#2B3B60"),
                ("Jungle Green", "#007248"),
                ("Pistachio Green", "#93A682"),
                ("Mango Yellow", "#F2B706"),
                ("Yellow Gold", "#9A8523"),
                ("Prusa Orange", "#EB5403"),
                ("Prusa Orange Transparent", "#F17230"),
                ("Anthracite Grey", "#3F4646"),
                ("Urban Grey", "#95908C"),
                ("Clear", "#E4E7E3"),
                ("Neon Green Transparent", "#A6EC5E"),
                ("Carmine Red Transparent", "#B5422F"),
                ("Shimmering Violet", "#1D1991"),
                ("Terracotta Light", "#B87F69"),
                ("Prusa Pro Green", "#00FA9A"),
                ("Recycled", "#0D210C"),
                ("Carbon Fiber Black", "#3B3539"),
            ], nozzle_default=240, bed_min=70, bed_default=85, price=29.99),
            # PETG Specialty
            *_colors("PETG", [
                ("Recycled Black", "#000000"),
                ("Magnetite 40% Grey", "#272E29"),
                ("Tungsten 75%", "#545251"),
                ("V0 Jet Black", "#363331"),
                ("V0 Natural", "#DEE2D8"),
            ], nozzle_default=240, bed_min=70, bed_default=85, price=49.99),
            *_colors("ASA", [
                ("Jet Black", "#292824"),
                ("Prusa Galaxy Black", "#3E413E"),
                ("Signal White", "#E3DFD7"),
                ("Natural", "#D6D6CB"),
                ("Lipstick Red", "#D03036"),
                ("Sapphire Blue", "#3B4467"),
                ("Prusa Orange", "#F55927"),
                ("Olive Green", "#617512"),
                ("Prusa Pro Green", "#00FA9A"),
            ], nozzle_min=240, nozzle_default=260, nozzle_max=270,
               bed_min=95, bed_default=110, bed_max=115,
               net_weight_g=850.0, price=34.99),
            *_colors("TPU", [
                ("95A Jet Black", "#232323"),
                ("95A Natural", "#F9F3E5"),
            ], price=39.99),
            *_colors("PLA", [
                ("Woodfill Chocolate Brown", "#543C27"),
                ("Woodfill Linden Light", "#DFBF9F"),
                ("Woodfill Pastel Brown", "#916E47"),
            ], nozzle_min=200, nozzle_default=215, nozzle_max=230,
               bed_min=40, bed_default=60, price=34.99),
        ],
    },

    # ── Bambu Lab ─────────────────────────────────────────────────────
    # Hex codes from official Bambu Lab hex code table PDFs and store pages
    {
        "name": "Bambu Lab",
        "website": "https://bambulab.com",
        "empty_spool_weight_g": 256.0,
        "filaments": [
            # PLA Basic
            *_colors("PLA", [
                ("Jade White", "#FFFFFF"),
                ("Black", "#000000"),
                ("Red", "#C12E1F"),
                ("Blue", "#1D3F8E"),
                ("Green", "#1B8A3E"),
                ("Yellow", "#F5D023"),
                ("Orange", "#ED6B21"),
                ("Grey", "#808080"),
                ("Magenta", "#EC008C"),
                ("Purple", "#5E43B7"),
                ("Bambu Green", "#00AE42"),
                ("Cyan", "#00B4D8"),
                ("Gold", "#E4BD68"),
                ("Pink", "#F5A0C0"),
                ("Brown", "#6B3A2A"),
                ("Beige", "#D4C5A9"),
                ("Mistletoe Green", "#3F8E43"),
                ("Pumpkin Orange", "#E5740B"),
                ("Sunflower Yellow", "#F0C800"),
                ("Indigo Purple", "#3C2E6B"),
                ("Hot Pink", "#E6348F"),
                ("Cocoa Brown", "#5C3A2D"),
                ("Silver", "#B0B0B0"),
                ("Bronze", "#8C6239"),
                ("Blue Grey", "#6E7F8D"),
            ], nozzle_min=190, nozzle_default=220, bed_default=55, price=22.99),
            # PLA Matte
            *_colors("PLA", [
                ("Matte Ivory White", "#FFFFFF"),
                ("Matte Bone White", "#CBC6B8"),
                ("Matte Desert Tan", "#E8DBB7"),
                ("Matte Charcoal", "#2C2C2C"),
                ("Matte Ash Grey", "#9E9E9E"),
                ("Matte Nardo Gray", "#6B6B6B"),
                ("Matte Sakura Pink", "#E0A8BB"),
                ("Matte Lilac Purple", "#B39DDB"),
                ("Matte Mandarin Orange", "#EF6C00"),
                ("Matte Lemon Yellow", "#FDD835"),
                ("Matte Scarlet Red", "#C62828"),
                ("Matte Dark Red", "#8B0000"),
                ("Matte Dark Brown", "#4E342E"),
                ("Matte Latte Brown", "#A0826D"),
                ("Matte Dark Green", "#1B5E20"),
                ("Matte Grass Green", "#43A047"),
                ("Matte Ice Blue", "#90CAF9"),
                ("Matte Marine Blue", "#0D47A1"),
                ("Matte Dark Blue", "#1A237E"),
                ("Matte Caramel", "#A1887F"),
                ("Matte Apple Green", "#7CB342"),
                ("Matte Plum", "#6A1B9A"),
            ], nozzle_min=190, nozzle_default=220, bed_default=55, price=24.99),
            # PLA Silk
            *_colors("PLA", [
                ("Silk Gold", "#D4A843"),
                ("Silk Silver", "#C0C0C0"),
                ("Silk Copper", "#B87333"),
                ("Silk Red", "#CC3333"),
                ("Silk Blue", "#336699"),
                ("Silk Green", "#339966"),
                ("Silk Purple", "#663399"),
            ], nozzle_min=190, nozzle_default=220, bed_default=55, price=29.99),
            # PETG Basic
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#F0F0F0"),
                ("Grey", "#7A7A7A"),
                ("Blue Grey", "#6E7F8D"),
                ("Red", "#B82020"),
                ("Blue", "#1E3A7A"),
                ("Green", "#2E7D32"),
                ("Orange", "#E65100"),
                ("Yellow", "#F9A825"),
                ("Gold", "#D4A843"),
                ("Purple", "#6A1B9A"),
                ("Lake Blue", "#0097A7"),
                ("Lime Green", "#7CB342"),
                ("Natural", "#E0DCD0"),
            ], nozzle_min=230, nozzle_default=245, bed_default=70, price=24.99),
            # PETG Translucent
            *_colors("PETG", [
                ("Translucent Clear", "#E0E0E0"),
                ("Translucent Light Blue", "#80D8FF"),
                ("Translucent Teal", "#009FA1"),
                ("Translucent Pink", "#F48FB1"),
                ("Translucent Orange", "#FFAB40"),
                ("Translucent Purple", "#9C27B0"),
                ("Translucent Olive", "#8BC34A"),
                ("Translucent Brown", "#795548"),
                ("Translucent Grey", "#9E9E9E"),
            ], nozzle_min=230, nozzle_default=245, bed_default=70, price=24.99),
            # ABS
            *_colors("ABS", [
                ("Black", "#1A1A1A"),
                ("White", "#F0F0F0"),
                ("Silver", "#B0B0B0"),
                ("Red", "#C62828"),
                ("Blue", "#1565C0"),
                ("Azure Blue", "#0288D1"),
                ("Navy Blue", "#0D47A1"),
                ("Grey", "#757575"),
                ("Bambu Green", "#00AE42"),
                ("Olive", "#827717"),
                ("Tangerine", "#F57C00"),
                ("Yellow", "#F9A825"),
                ("Orange", "#E65100"),
            ], nozzle_min=240, nozzle_default=260, nozzle_max=270,
               bed_min=90, bed_default=100, price=27.99),
            # ASA
            *_colors("ASA", [
                ("Black", "#1A1A1A"),
                ("White", "#F0F0F0"),
                ("Grey", "#757575"),
                ("Red", "#C62828"),
                ("Blue", "#1565C0"),
                ("Green", "#2E7D32"),
                ("Orange", "#E65100"),
                ("Yellow", "#F9A825"),
            ], nozzle_min=240, nozzle_default=260, nozzle_max=270,
               bed_min=90, bed_default=100, price=29.99),
            # TPU
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("White", "#F0F0F0"),
                ("Red", "#C62828"),
                ("Blue", "#1565C0"),
            ], price=34.99),
        ],
    },

    # ── Elegoo ────────────────────────────────────────────────────────
    # Hex codes from MakerWorld swatch set and filamentcolors.xyz
    {
        "name": "Elegoo",
        "website": "https://us.elegoo.com",
        "empty_spool_weight_g": 154.0,
        "filaments": [
            # PLA Standard
            *_colors("PLA", [
                ("Black", "#000000"),
                ("White", "#FFFFFF"),
                ("Grey", "#8F949B"),
                ("Space Grey", "#5D5D5D"),
                ("True Red", "#E60012"),
                ("Red", "#EA140E"),
                ("Burgundy", "#800020"),
                ("Blue", "#0047AB"),
                ("Light Blue", "#6CB4EE"),
                ("Dark Blue", "#2240AF"),
                ("Sky Blue", "#27B2D0"),
                ("Green", "#228B22"),
                ("Sea Green", "#1ABC83"),
                ("Neon Green", "#08E327"),
                ("Yellow", "#F6D701"),
                ("Orange", "#FD7C18"),
                ("Purple", "#603BA0"),
                ("Silver", "#C0C0C0"),
                ("Beige", "#D2B48C"),
                ("Brown", "#6B3A2A"),
                ("Hot Pink", "#FF69B4"),
                ("Pink", "#F9B0BD"),
                ("Clear", "#E9E9E7"),
                ("Wood Color", "#B19870"),
            ], nozzle_default=210, bed_default=60, price=13.99),
            # PLA+
            *_colors("PLA+", [
                ("Black", "#000000"),
                ("White", "#FFFFFF"),
                ("Grey", "#8F949B"),
                ("Space Grey", "#5D5D5D"),
                ("Red", "#EA140E"),
                ("Dark Blue", "#2240AF"),
                ("Sky Blue", "#27B2D0"),
                ("Sea Green", "#1ABC83"),
                ("Neon Green", "#08E327"),
                ("Yellow", "#F6D701"),
                ("Orange", "#FD7C18"),
                ("Purple", "#603BA0"),
                ("Pink", "#F9B0BD"),
                ("Beige", "#D2B48C"),
                ("Brown", "#6B3A2A"),
                ("Translucent", "#E0E0E0"),
                ("Wood Color", "#B19870"),
            ], price=18.99),
            # PLA Pro
            *_colors("PLA", [
                ("Pro Black", "#1A1A1A"),
                ("Pro White", "#FFFFFF"),
                ("Pro Burgundy", "#800020"),
                ("Pro Red", "#CC0000"),
                ("Pro True Red", "#E60012"),
                ("Pro Blue", "#0047AB"),
                ("Pro Light Blue", "#6CB4EE"),
                ("Pro Green", "#228B22"),
                ("Pro Neon Green", "#08E327"),
                ("Pro Yellow", "#F6D701"),
                ("Pro Grey", "#808080"),
                ("Pro Purple", "#603BA0"),
                ("Pro Silver", "#C0C0C0"),
                ("Pro Beige", "#D2B48C"),
                ("Pro Hot Pink", "#FF69B4"),
            ], nozzle_default=210, bed_default=60, price=16.99),
            # PLA Matte
            *_colors("PLA", [
                ("Matte Navy Blue", "#003366"),
                ("Matte Black", "#2A2A2A"),
                ("Matte White", "#F0F0F0"),
                ("Matte Slate Grey", "#708090"),
                ("Matte Beige", "#D2B48C"),
                ("Matte Teal Green", "#2E8B7A"),
                ("Matte Ruby Red", "#9B2335"),
                ("Matte Sunshine Yellow", "#F5C518"),
                ("Matte Lavender Purple", "#967BB6"),
                ("Matte Sakura Pink", "#F2A7BB"),
                ("Matte Ice Blue", "#B0D9E8"),
                ("Matte Mint Green", "#98E4C1"),
                ("Matte Earth Brown", "#8B5E3C"),
                ("Matte Orange", "#E8720C"),
            ], nozzle_default=210, bed_default=60, price=17.99),
            # PLA Silk
            *_colors("PLA", [
                ("Silk Blue Magenta", "#7030A0"),
                ("Silk Gold", "#D4A843"),
                ("Silk Silver Grey", "#9E9E9E"),
                ("Silk Copper", "#B87333"),
                ("Silk Red", "#CC3333"),
                ("Silk White", "#F0F0F0"),
                ("Silk Coral Pink", "#F08080"),
                ("Silk Mint Green", "#98E4C1"),
                ("Silk Holly Green", "#2E8B57"),
                ("Silk Green Red", "#8B0000"),
                ("Silk Black Red", "#3A0A0A"),
                ("Silk Black Purple", "#2D1B3D"),
                ("Silk Blue Green", "#2E8B8B"),
                ("Silk Blue Purple", "#4A3A8B"),
                ("Silk Sky Blue", "#87CEEB"),
                ("Silk Bluish Purple", "#6A5ACD"),
                ("Silk Peach Pink", "#FFCBA4"),
                ("Silk True Red", "#E60012"),
                ("Silk Yellow Purple", "#8B6914"),
                ("Silk Black Green", "#0A2A0A"),
                ("Silk Blue Purple Black", "#1A0A2E"),
                ("Silk Blue Green Orange", "#4A7A6A"),
            ], nozzle_default=210, bed_default=60, price=18.99),
            # PLA Galaxy
            *_colors("PLA", [
                ("Galaxy Purple", "#2D1B69"),
                ("Galaxy Black", "#1A1A2E"),
                ("Galaxy Peacock Blue", "#005F73"),
            ], nozzle_default=210, bed_default=60, price=18.99),
            # PLA Sparkle
            *_colors("PLA", [
                ("Sparkle Black", "#1A1A1A"),
                ("Sparkle Gold", "#D4A843"),
                ("Sparkle Green", "#1B4D2E"),
                ("Sparkle Red", "#8B0000"),
                ("Sparkle Dark Grey", "#404040"),
                ("Sparkle Turquoise", "#00827F"),
                ("Sparkle Purplish Grey", "#7B6F8A"),
            ], nozzle_default=210, bed_default=60, price=18.99),
            # PLA Metallic
            *_colors("PLA", [
                ("Metallic Gold", "#D4A843"),
                ("Metallic Bronze", "#8C6239"),
                ("Metallic Blue", "#1A3A6B"),
                ("Metallic Green", "#1B4D2E"),
            ], nozzle_default=210, bed_default=60, price=18.99),
            # PLA Marble / Wood / Glow / CF
            *_colors("PLA", [
                ("Marble", "#E0DCD0"),
                ("Marble Brick Red", "#9B2335"),
                ("Marble Cement Grey", "#8A8A8A"),
                ("Wood Filled", "#8B6239"),
                ("Wood Light Brown", "#C4A484"),
                ("Wood Walnut", "#5C3317"),
                ("Wood Rosewood", "#8B2252"),
                ("Wood Tan Birch", "#D2B48C"),
                ("Glow Blue", "#89CFF0"),
                ("Glow Green", "#39FF14"),
                ("Glow Yellow", "#FFFF00"),
                ("Glow Orange", "#FF7F00"),
                ("Glow Pink", "#FF69B4"),
                ("Carbon Fiber Black", "#1A1A1A"),
                ("Carbon Fiber Grey", "#4A4A4A"),
            ], nozzle_default=210, bed_default=60, price=18.99),
            # Rapid PLA+
            *_colors("PLA+", [
                ("Rapid Black", "#000000"),
                ("Rapid White", "#FFFFFF"),
                ("Rapid Grey", "#808080"),
                ("Rapid Blue", "#0047AB"),
                ("Rapid Green", "#228B22"),
                ("Rapid Red", "#CC0000"),
                ("Rapid Orange", "#FD7C18"),
                ("Rapid Yellow", "#F6D701"),
                ("Rapid Silver", "#C0C0C0"),
                ("Rapid Brown", "#6B3A2A"),
                ("Rapid Beige", "#D2B48C"),
            ], nozzle_default=210, bed_default=60, price=16.99),
            # Rapid PETG
            *_colors("PETG", [
                ("Rapid Black", "#1A1A1A"),
                ("Rapid White", "#F0F0F0"),
                ("Rapid Grey", "#808080"),
                ("Rapid Space Grey", "#5D5D5D"),
                ("Rapid Blue", "#0047AB"),
                ("Rapid Green", "#228B22"),
                ("Rapid Red", "#CC0000"),
                ("Rapid Orange", "#FD7C18"),
                ("Rapid Yellow", "#F6D701"),
                ("Rapid Brown", "#6B3A2A"),
                ("Rapid Beige", "#D2B48C"),
                ("Rapid Transparent", "#E0E0E0"),
            ], nozzle_default=240, bed_default=70, price=16.99),
            # PETG Pro
            *_colors("PETG", [
                ("Pro Black", "#1A1A1A"),
                ("Pro White", "#F0F0F0"),
                ("Pro Blue", "#0047AB"),
                ("Pro Grey", "#808080"),
                ("Pro Silver", "#C0C0C0"),
                ("Pro Pink", "#F9B0BD"),
                ("Pro Red", "#CC0000"),
                ("Pro Olive Green", "#6B8E23"),
                ("Pro Burgundy Red", "#800020"),
                ("Pro Light Blue", "#6CB4EE"),
                ("Pro Green", "#228B22"),
                ("Pro Yellow", "#F6D701"),
                ("Pro Purple", "#603BA0"),
            ], nozzle_default=240, bed_default=70, price=19.99),
            # ABS
            *_colors("ABS", [
                ("Black", "#000000"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Grey", "#808080"),
                ("Blue", "#0047AB"),
                ("Orange", "#FD7C18"),
                ("Yellow", "#F6D701"),
                ("Green", "#228B22"),
                ("Purple", "#603BA0"),
                ("Pink", "#F9B0BD"),
                ("Cyan", "#00BCD4"),
                ("Olive Green", "#6B8E23"),
                ("Sky Blue", "#27B2D0"),
                ("Orange Yellow", "#F5A623"),
                ("Navy Blue", "#003366"),
            ], nozzle_default=245, bed_default=100, price=19.99),
            # ASA
            *_colors("ASA", [
                ("Black", "#000000"),
                ("White", "#FFFFFF"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Grey", "#808080"),
                ("Red", "#CC0000"),
            ], nozzle_default=255, bed_default=105, price=21.99),
            # TPU 95A
            *_colors("TPU", [
                ("Black", "#000000"),
                ("White", "#FFFFFF"),
                ("Translucent", "#E0E0E0"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Grey", "#808080"),
            ], price=24.99),
        ],
    },

    # ── Hatchbox ──────────────────────────────────────────────────────
    {
        "name": "Hatchbox",
        "website": "https://www.hatchbox3d.com",
        "empty_spool_weight_g": 225.0,
        "filaments": [
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Cool Gray", "#808080"),
                ("Silver", "#C0C0C0"),
                ("Pink", "#FF69B4"),
                ("Purple", "#7B2D8E"),
                ("Gold", "#CFB53B"),
                ("Copper", "#B87333"),
                ("Mint Green", "#98FF98"),
                ("Light Blue", "#87CEEB"),
                ("Midnight Purple", "#2D1B4E"),
                ("Iron Red", "#8B2500"),
                ("Glow in the Dark", "#C8E6C9"),
                ("Glow in the Dark Blue", "#90CAF9"),
                ("Wood", "#B19870"),
                # Matte finishes
                ("Black Matte", "#2A2A2A"),
                ("White Matte", "#F0F0F0"),
                ("Navy Matte", "#003366"),
                ("Ash Gray Matte", "#6E6E6E"),
                ("Olive Matte", "#6B8E23"),
                # Metallic finishes
                ("Metallic Finish Gray", "#8A8A8A"),
                ("Metallic Finish Black", "#3A3A3A"),
                ("Silk Light Blue", "#80D8FF"),
            ], nozzle_min=180, nozzle_default=200, nozzle_max=220,
               bed_min=20, bed_default=50, price=28.00),
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#F0F0F0"),
                ("Red", "#CC0000"),
                ("Orange", "#FF6600"),
                ("Silver", "#C0C0C0"),
                ("Transparent White", "#F5F5F5"),
                ("Gray Blue", "#6E7F8D"),
                ("Natural", "#F0EDE0"),
                ("Green", "#228B22"),
                ("Lake Blue", "#0097A7"),
                ("Blue", "#0047AB"),
                ("Copper", "#B87333"),
                ("Bronze", "#8C6239"),
                ("Peacock Blue", "#005F6B"),
                ("Lime Green", "#32CD32"),
                ("Gold", "#CFB53B"),
                ("Purple", "#7B2D8E"),
                ("Pink", "#FF69B4"),
                ("Dark Yellow", "#D4A843"),
                ("Mint Green", "#98FF98"),
                ("Chocolate", "#6B3A2A"),
                ("Light Orange", "#FFB347"),
                ("Brown", "#795548"),
                ("Baby Blue", "#89CFF0"),
                ("Yellow", "#FFD700"),
                ("Light Brown", "#C4A484"),
                ("Dark Green", "#006400"),
            ], nozzle_default=240, bed_default=80, price=26.00),
            *_colors("ABS", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
            ], nozzle_min=210, nozzle_default=235, nozzle_max=250,
               bed_min=80, bed_default=100, price=25.00),
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Baby Blue", "#89CFF0"),
                ("Beige", "#D2B48C"),
                ("Red", "#CC0000"),
            ], price=32.00),
        ],
    },

    # ── eSUN ──────────────────────────────────────────────────────────
    {
        "name": "eSUN",
        "website": "https://www.esun3d.com",
        "empty_spool_weight_g": 224.0,
        "filaments": [
            *_colors("PLA+", [
                ("Black", "#1A1A1A"),
                ("Cool White", "#F0F5FF"),
                ("Warm White", "#F5F0E0"),
                ("Bone White", "#E3DAC9"),
                ("Fire Engine Red", "#CE2029"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Light Blue", "#6CB4EE"),
                ("Dark Blue", "#003366"),
                ("Green", "#228B22"),
                ("Pine Green", "#01796F"),
                ("Peak Green", "#4CAF50"),
                ("Olive Green", "#6B8E23"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Silver", "#C0C0C0"),
                ("Purple", "#7B2D8E"),
                ("Magenta", "#FF00FF"),
                ("Pink", "#FF69B4"),
                ("Brown", "#6B3A2A"),
                ("Light Brown", "#C4A484"),
                ("Skin/Beige", "#FFCBA4"),
                ("Gold", "#CFB53B"),
                ("Luminous Green", "#39FF14"),
                ("Luminous Blue", "#1B03A3"),
            ], price=18.99),
            *_colors("PETG", [
                ("Solid Black", "#1A1A1A"),
                ("Solid White", "#FFFFFF"),
                ("Solid Grey", "#808080"),
                ("Solid Red", "#CC0000"),
                ("Solid Gold", "#CFB53B"),
                ("Solid Blue", "#0047AB"),
                ("Solid Green", "#228B22"),
                ("Solid Yellow", "#FFD700"),
                ("Solid Silver", "#C0C0C0"),
                ("Solid Purple", "#7B2D8E"),
                ("Fire Engine Red", "#CE2029"),
                ("Natural", "#F0EDE0"),
                ("Translucent Green", "#4CAF50"),
                ("Translucent Blue", "#42A5F5"),
                ("Translucent Yellow", "#FFEE58"),
                ("Translucent Magenta", "#EC407A"),
            ], nozzle_min=230, nozzle_default=240, nozzle_max=250,
               bed_default=80, price=21.99),
            *_colors("ABS+", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Natural", "#F0EDE0"),
                ("Brown", "#6B3A2A"),
                ("Purple", "#7B2D8E"),
                ("Pink", "#FF69B4"),
                ("Silver", "#C0C0C0"),
            ], price=19.99),
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Blue", "#0047AB"),
                ("Red", "#CC0000"),
                ("Transparent", "#E0E0E0"),
            ], price=24.99),
            *_colors("ASA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Gray", "#808080"),
                ("Blue", "#0047AB"),
                ("Red", "#CC0000"),
                ("Orange", "#FF6600"),
                ("Yellow", "#FFD700"),
                ("Green", "#228B22"),
                ("Natural", "#F0EDE0"),
            ], price=22.99),
        ],
    },

    # ── Polymaker ─────────────────────────────────────────────────────
    # Hex codes from Polymaker product pages & Panchroma line
    {
        "name": "Polymaker",
        "website": "https://polymaker.com",
        "empty_spool_weight_g": 145.0,
        "filaments": [
            # PolyLite PLA Pro
            *_colors("PLA", [
                ("Black", "#0C0E0C"),
                ("White", "#E6E1DE"),
                ("Cold White", "#EAECF5"),
                ("Orange", "#EC6A01"),
                ("Army Beige", "#AA6F3E"),
                ("Yellow", "#F7B300"),
                ("Light Yellow", "#F3D561"),
                ("Army Green", "#665A28"),
                ("Light Green", "#BBD39B"),
                ("Green", "#178D4A"),
                ("Polymaker Teal", "#2FA5AE"),
                ("Blue-Green", "#00272F"),
                ("Light Blue", "#72AECB"),
                ("Blue", "#00307E"),
                ("Grey", "#73767D"),
                ("Dark Grey", "#4A4A4A"),
                ("Purple", "#7B2D8E"),
                ("Dark Purple", "#4B0082"),
                ("Magenta", "#FF00FF"),
                ("Pink", "#FF69B4"),
                ("Light Red", "#E57373"),
                ("Red", "#CC0000"),
                ("Brown", "#795548"),
            ], density=1.19, nozzle_default=210, bed_default=50, price=19.99),
            # Panchroma Matte PLA (formerly PolyTerra PLA)
            *_colors("PLA", [
                ("Matte Charcoal Black", "#1C1C1C"),
                ("Matte Cotton White", "#E6DDDB"),
                ("Matte Ash Grey", "#9E9E9E"),
                ("Matte Fossil Grey", "#6F727E"),
                ("Matte Army Beige", "#CCA897"),
                ("Matte Army Brown", "#724E3D"),
                ("Matte Earth Brown", "#7C594A"),
                ("Matte Muted White", "#AFA198"),
                ("Matte Pastel Peanut", "#C29572"),
                ("Matte Wood Brown", "#AD7441"),
                ("Matte Pastel Peach", "#F2B67A"),
                ("Matte Sunrise Orange", "#F78E0E"),
                ("Matte Pastel Banana", "#F5CF6F"),
                ("Matte Army Light Green", "#A78403"),
                ("Matte Savannah Yellow", "#F0BE02"),
                ("Matte Lime Green", "#D0E740"),
                ("Matte Army Dark Green", "#515234"),
                ("Matte Pastel Mint", "#BEC9A5"),
                ("Matte Muted Green", "#656D60"),
                ("Matte Forest Green", "#519F61"),
                ("Matte Arctic Teal", "#5AABB1"),
                ("Matte Pastel Ice", "#95C5D3"),
                ("Matte Sapphire Blue", "#005AA2"),
                ("Matte Army Blue", "#062B4D"),
                ("Matte Muted Blue", "#4E6A84"),
                ("Matte Lavender Purple", "#8A68B5"),
                ("Matte Muted Purple", "#7C5577"),
                ("Matte Army Purple", "#5B3A6B"),
                ("Matte Pastel Candy", "#DABCC8"),
                ("Matte Sakura Pink", "#E0A8BB"),
                ("Matte Pastel Watermelon", "#E93A3F"),
                ("Matte Lava Red", "#DE1619"),
                ("Matte Army Red", "#AC1A17"),
                ("Matte Muted Red", "#DB3E14"),
                ("Matte Lotus Pink", "#E8829B"),
                ("Matte Sky Blue", "#5CA8D6"),
                ("Matte Electric Indigo", "#4B0082"),
                ("Matte Pastel Periwinkle", "#A8B8E0"),
            ], density=1.19, nozzle_default=210, bed_default=50, price=17.99),
            # Panchroma Silk PLA
            *_colors("PLA", [
                ("Silk Gold", "#D4A843"),
                ("Silk Silver", "#C0C0C0"),
                ("Silk Copper", "#B87333"),
                ("Silk Bronze", "#CD7F32"),
                ("Silk Red", "#CC3333"),
                ("Silk Blue", "#336699"),
                ("Silk Green", "#339966"),
                ("Silk Purple", "#7B2D8E"),
                ("Silk Pink", "#FF69B4"),
                ("Silk Rose Gold", "#B76E79"),
                ("Silk Champagne", "#F7E7CE"),
                ("Silk Lemon Yellow", "#FFF44F"),
                ("Silk Orange", "#FF8C00"),
                ("Silk Teal", "#008080"),
                ("Silk Dark Green", "#006400"),
                ("Silk Navy Blue", "#003366"),
                ("Silk Violet", "#7F00FF"),
                ("Silk Burgundy", "#800020"),
                ("Silk White", "#F0F0F0"),
                ("Silk Black", "#1A1A1A"),
                ("Silk Sakura", "#FFB7C5"),
                ("Silk Ivory", "#FFFFF0"),
                ("Silk Ruby", "#E0115F"),
                ("Silk Jade", "#00A86B"),
            ], density=1.19, nozzle_default=210, bed_default=50, price=19.99),
            # Panchroma Satin PLA
            *_colors("PLA", [
                ("Satin White", "#F0F0F0"),
                ("Satin Black", "#1A1A1A"),
                ("Satin Grey", "#808080"),
                ("Satin Blue", "#0047AB"),
                ("Satin Green", "#228B22"),
                ("Satin Red", "#CC0000"),
                ("Satin Orange", "#FF6600"),
                ("Satin Yellow", "#FFD700"),
                ("Satin Purple", "#7B2D8E"),
                ("Satin Pink", "#FF69B4"),
            ], density=1.19, nozzle_default=210, bed_default=50, price=18.99),
            # PolyMax PLA (tough/impact resistant)
            *_colors("PLA", [
                ("Max Black", "#1A1A1A"),
                ("Max White", "#FFFFFF"),
                ("Max Red", "#CC0000"),
                ("Max Blue", "#0047AB"),
                ("Max Green", "#228B22"),
                ("Max Yellow", "#FFD700"),
                ("Max Orange", "#FF6600"),
                ("Max Grey", "#808080"),
                ("Max Purple", "#7B2D8E"),
                ("Max Teal", "#008080"),
                ("Max True Black", "#0C0E0C"),
                ("Max Cosmopolitan White", "#E6E1DE"),
            ], density=1.19, nozzle_default=210, bed_default=50, price=29.99),
            # PolySmooth PVB (smoothable with IPA)
            *_colors("PLA", [
                ("Smooth Black", "#1A1A1A"),
                ("Smooth White", "#FFFFFF"),
                ("Smooth Red", "#CC0000"),
                ("Smooth Blue", "#0047AB"),
                ("Smooth Grey", "#808080"),
                ("Smooth Orange", "#FF6600"),
                ("Smooth Yellow", "#FFD700"),
                ("Smooth Green", "#228B22"),
                ("Smooth Teal", "#008080"),
                ("Smooth Purple", "#7B2D8E"),
                ("Smooth Pink", "#FF69B4"),
                ("Smooth Skin", "#DEB887"),
            ], density=1.19, nozzle_default=210, bed_default=50, price=29.99),
            # Metallic PLA Pro
            *_colors("PLA", [
                ("Metallic Galaxy Purple", "#4A0080"),
                ("Metallic Starlight Gold", "#D4A843"),
                ("Metallic Starlight Silver", "#C0C0C0"),
                ("Metallic Starlight Bronze", "#CD7F32"),
                ("Metallic Starlight Copper", "#B87333"),
                ("Metallic Iron Grey", "#5A5A5A"),
                ("Metallic Champagne", "#F7E7CE"),
                ("Metallic Midnight Blue", "#003366"),
                ("Metallic Ruby Red", "#9B111E"),
            ], density=1.19, nozzle_default=210, bed_default=50, price=24.99),
            # LW-PLA (lightweight/foaming)
            *_colors("PLA", [
                ("LW Black", "#1A1A1A"),
                ("LW White", "#FFFFFF"),
                ("LW Red", "#CC0000"),
                ("LW Blue", "#0047AB"),
                ("LW Yellow", "#FFD700"),
                ("LW Grey", "#808080"),
                ("LW Orange", "#FF6600"),
            ], density=0.65, nozzle_default=230, nozzle_min=200, nozzle_max=260, bed_default=50, price=34.99),
            # PolyLite PETG
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Dark Blue", "#003366"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Dark Grey", "#4A4A4A"),
                ("Silver Grey", "#A8A8A8"),
                ("Purple", "#7B2D8E"),
                ("Teal", "#008080"),
                ("Pink", "#FF69B4"),
                ("Transparent", "#E0E0E0"),
                ("Natural", "#F0EDE0"),
                ("Transparent Blue", "#42A5F5"),
                ("Transparent Green", "#66BB6A"),
                ("Warm Grey", "#A0887E"),
                ("True White", "#FAFAFA"),
                ("Army Beige", "#AA6F3E"),
                ("Brown", "#795548"),
                ("Light Blue", "#72AECB"),
                ("Magenta", "#FF00FF"),
                ("Lime Green", "#AACC00"),
                ("Gold", "#CFB53B"),
            ], nozzle_min=230, nozzle_default=245, bed_default=80, price=19.99),
            # PolyLite ASA
            *_colors("ASA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Grey", "#808080"),
                ("Orange", "#FF6600"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Dark Grey", "#4A4A4A"),
                ("Teal", "#008080"),
                ("Purple", "#7B2D8E"),
                ("Pink", "#FF69B4"),
                ("Brown", "#795548"),
                ("Beige", "#CCA897"),
                ("Light Blue", "#72AECB"),
                ("Natural", "#F0EDE0"),
                ("Army Green", "#665A28"),
                ("Dark Blue", "#003366"),
                ("Lime Green", "#AACC00"),
                ("Light Green", "#BBD39B"),
                ("Silver Grey", "#A8A8A8"),
                ("Tan", "#D2B48C"),
                ("Warm Grey", "#A0887E"),
                ("Magenta", "#FF00FF"),
                ("True Black", "#0C0E0C"),
            ], price=24.99),
            # PolyFlex TPU95
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
            ], price=32.99),
        ],
    },

    # ── Fiberon (by Polymaker) ───────────────────────────────────────
    # High-performance composite filaments — engineering / industrial use
    # Hex codes approximated (Polymaker does not publish hex for Fiberon)
    {
        "name": "Fiberon",
        "website": "https://fiberon.polymaker.com",
        "empty_spool_weight_g": 200.0,
        "filaments": [
            # ASA-CF08 (ASA + 8% carbon fiber) — 6 colors
            *_colors("ASA", [
                ("ASA-CF08 Black", "#1A1A1A"),
                ("ASA-CF08 Dark Grey", "#3A3A3A"),
                ("ASA-CF08 Light Grey", "#A0A0A0"),
                ("ASA-CF08 Desert Sand", "#C2A87D"),
                ("ASA-CF08 Dark Red", "#8B1A1A"),
                ("ASA-CF08 Navy Blue", "#003366"),
            ], nozzle_min=260, nozzle_default=270, nozzle_max=280,
               bed_min=90, bed_default=95, bed_max=100,
               tensile_strength_mpa=43.5, net_weight_g=500.0, price=19.99),
            # PETG-rCF08 (PETG + 8% recycled carbon fiber)
            *_colors("PETG", [
                ("PETG-rCF08 Black", "#1A1A1A"),
            ], nozzle_min=240, nozzle_default=255, nozzle_max=270,
               bed_min=60, bed_default=65, bed_max=70,
               tensile_strength_mpa=59.8, net_weight_g=500.0, price=19.99),
            # PETG-ESD (PETG + carbon nanotubes, ESD-safe)
            *_colors("PETG", [
                ("PETG-ESD Black", "#1A1A1A"),
            ], nozzle_min=250, nozzle_default=270, nozzle_max=290,
               bed_min=70, bed_default=75, bed_max=80,
               tensile_strength_mpa=36.1, net_weight_g=500.0, price=32.99),
            # PET-CF17 (PET + 17% carbon fiber)
            *_colors("PETG", [
                ("PET-CF17 Black", "#1A1A1A"),
            ], nozzle_min=270, nozzle_default=285, nozzle_max=300,
               bed_min=70, bed_default=75, bed_max=80,
               tensile_strength_mpa=65.9, net_weight_g=500.0, price=24.99),
            # PET-GF15 (PET + 15% glass fiber) — 6 colors
            *_colors("PETG", [
                ("PET-GF15 Black", "#1A1A1A"),
                ("PET-GF15 White", "#FFFFFF"),
                ("PET-GF15 Blue", "#0047AB"),
                ("PET-GF15 Dark Grey", "#4A4A4A"),
                ("PET-GF15 Light Grey", "#A0A0A0"),
                ("PET-GF15 Red", "#CC0000"),
            ], nozzle_min=280, nozzle_default=295, nozzle_max=310,
               bed_min=70, bed_default=75, bed_max=80,
               tensile_strength_mpa=59.9, net_weight_g=1000.0, price=29.99),
            # PA6-CF20 (Nylon 6 + 20% carbon fiber) — strongest Fiberon
            *_colors("PETG", [
                ("PA6-CF20 Black", "#1A1A1A"),
            ], nozzle_min=280, nozzle_default=290, nozzle_max=300,
               bed_min=40, bed_default=45, bed_max=50,
               density=1.22, tensile_strength_mpa=109.0, net_weight_g=500.0, price=39.99),
            # PA6-GF25 (Nylon 6 + 25% glass fiber)
            *_colors("PETG", [
                ("PA6-GF25 Grey", "#808080"),
            ], nozzle_min=280, nozzle_default=290, nozzle_max=300,
               bed_min=40, bed_default=45, bed_max=50,
               density=1.36, tensile_strength_mpa=80.1, net_weight_g=500.0, price=29.99),
            # PA12-CF10 (Nylon 12 + 10% carbon fiber)
            *_colors("PETG", [
                ("PA12-CF10 Black", "#1A1A1A"),
            ], nozzle_min=280, nozzle_default=290, nozzle_max=300,
               bed_min=40, bed_default=45, bed_max=50,
               density=1.16, tensile_strength_mpa=77.4, net_weight_g=500.0, price=69.99),
            # PA612-CF15 (Nylon 612 + 15% carbon fiber)
            *_colors("PETG", [
                ("PA612-CF15 Black", "#1A1A1A"),
            ], nozzle_min=250, nozzle_default=275, nozzle_max=300,
               bed_min=40, bed_default=45, bed_max=50,
               density=1.20, tensile_strength_mpa=91.9, net_weight_g=500.0, price=34.99),
            # PA612-ESD (Nylon 612 + CF + CNT, ESD-safe)
            *_colors("PETG", [
                ("PA612-ESD Black", "#1A1A1A"),
            ], nozzle_min=280, nozzle_default=300, nozzle_max=320,
               bed_min=40, bed_default=45, bed_max=50,
               density=1.18, tensile_strength_mpa=84.3, net_weight_g=500.0, price=64.99),
            # PPS-CF10 (PPS + 10% carbon fiber) — ultra performance
            *_colors("PETG", [
                ("PPS-CF10 Black", "#1A1A1A"),
            ], nozzle_min=310, nozzle_default=330, nozzle_max=350,
               bed_min=80, bed_default=85, bed_max=90,
               density=1.42, tensile_strength_mpa=32.0, net_weight_g=500.0, price=69.99),
            # PPS-GF20 (PPS + 20% glass fiber) — highest HDT (236°C)
            *_colors("PETG", [
                ("PPS-GF20 Neutral Grey", "#A0A0A0"),
            ], nozzle_min=310, nozzle_default=330, nozzle_max=350,
               bed_min=80, bed_default=85, bed_max=90,
               density=1.60, tensile_strength_mpa=64.0, net_weight_g=500.0, price=59.99),
        ],
    },

    # ── Overture ──────────────────────────────────────────────────────
    {
        "name": "Overture",
        "website": "https://overture3d.com",
        "empty_spool_weight_g": 237.0,
        "filaments": [
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Cold White", "#F0F5FF"),
                ("Red", "#CC0000"),
                ("Fresh Red", "#FF3333"),
                ("Blue", "#0047AB"),
                ("Light Blue", "#87CEEB"),
                ("Gray Blue", "#6E7F8D"),
                ("Green", "#228B22"),
                ("Olive Green", "#6B8E23"),
                ("Yellow", "#FFD700"),
                ("Highlight Yellow", "#FFFF00"),
                ("Orange", "#FF6600"),
                ("Space Gray", "#4A4A4A"),
                ("Light Gray", "#C0C0C0"),
                ("Cement Gray", "#999999"),
                ("Pink", "#FF69B4"),
                ("Purple", "#7B2D8E"),
                ("Gold", "#CFB53B"),
                ("Royal Gold", "#CFB53B"),
                ("Brown", "#6B3A2A"),
                ("Chocolate", "#5C3317"),
                ("Glow in Dark", "#C8E6C9"),
                ("Rainbow", "#FF6600"),
                # Gradient / Specialty
                ("Aurora Berry", "#9C27B0"),
                ("Avocado", "#87A96B"),
                ("Tequila Sunrise", "#FF8C00"),
                ("Lemon Yellow", "#FFF44F"),
                ("Metallic Gray", "#8A8A8A"),
                ("Northern Lights", "#78FFD6"),
                ("Rocket Pop", "#FF0000"),
                ("Sparkle Black", "#1A1A1A"),
                ("Sparkle Purple", "#6A0DAD"),
                ("Champagne Frost", "#F7E7CE"),
                ("Christmas Prism", "#CC0000"),
            ], nozzle_default=210, bed_default=55, price=14.99),
            # Matte PLA
            *_colors("PLA", [
                ("Matte White", "#F0F0F0"),
                ("Matte Black", "#2A2A2A"),
                ("Matte Pink", "#E91E63"),
                ("Matte Carbon Fiber Black", "#333333"),
            ], nozzle_default=210, bed_default=55, price=16.99),
            # Silk PLA
            *_colors("PLA", [
                ("Silk Gold", "#D4A843"),
                ("Silk Copper", "#B87333"),
                ("Silk Gray", "#8A8A8A"),
                ("Silk Silver", "#C0C0C0"),
                ("Silk White", "#F0F0F0"),
                ("Silk Red", "#CC3333"),
            ], nozzle_default=210, bed_default=55, price=16.99),
            # Easy PLA
            *_colors("PLA", [
                ("Easy Black", "#1A1A1A"),
                ("Easy White", "#FFFFFF"),
                ("Easy Space Gray", "#4A4A4A"),
                ("Easy Rock White", "#F5F5DC"),
                ("Easy Red", "#CC0000"),
                ("Easy Orange", "#FF6600"),
            ], nozzle_default=210, bed_default=55, price=13.99),
            # PETG
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Rock White", "#F5F5DC"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Orange", "#FF6600"),
                ("Space Gray", "#4A4A4A"),
                ("Light Gray", "#C0C0C0"),
                ("Yellow", "#FFD700"),
                ("Purple", "#7B2D8E"),
                ("Transparent", "#E0E0E0"),
            ], nozzle_min=230, nozzle_default=240, nozzle_max=250,
               bed_default=80, price=14.99),
            # TPU
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Blue", "#0047AB"),
                ("Red", "#CC0000"),
                ("Brown", "#795548"),
            ], price=18.99),
        ],
    },

    # ── Inland (Micro Center) ─────────────────────────────────────────
    {
        "name": "Inland",
        "website": "https://www.microcenter.com",
        "empty_spool_weight_g": 142.0,
        "filaments": [
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Cold White", "#F0F5FF"),
                ("Bone White", "#E3DAC9"),
                ("Red", "#CC0000"),
                ("Bright Red", "#FF0000"),
                ("Blue", "#0047AB"),
                ("Dark Blue", "#003366"),
                ("Light Blue", "#87CEEB"),
                ("Cornflower Blue", "#6495ED"),
                ("Cyan", "#00BCD4"),
                ("Inland Blue", "#0066CC"),
                ("Green", "#228B22"),
                ("Ever Green", "#028A0F"),
                ("Forest Green", "#228B22"),
                ("Lime", "#32CD32"),
                ("Yellow", "#FFD700"),
                ("Dark Yellow", "#DAA520"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Dark Gray", "#4A4A4A"),
                ("Silver", "#C0C0C0"),
                ("Purple", "#7B2D8E"),
                ("Dark Purple", "#4B0082"),
                ("Pink", "#FF69B4"),
                ("Light Pink", "#FFB6C1"),
                ("Coral", "#FF7F50"),
                ("Brown", "#6B3A2A"),
                ("Light Brown", "#C4A484"),
                ("Chocolate", "#5C3317"),
                ("Copper", "#B87333"),
                ("Gold", "#CFB53B"),
                ("Magenta", "#FF00FF"),
                ("Khaki", "#C3B091"),
                ("Beige", "#D2B48C"),
                ("Denim", "#1560BD"),
                ("Light Olive", "#6B8E23"),
                ("Banana", "#FFE135"),
            ], nozzle_default=210, bed_default=55, price=12.99),
            *_colors("PLA+", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Bone White", "#E3DAC9"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Silver", "#C0C0C0"),
                ("Purple", "#7B2D8E"),
                ("Pink", "#FF69B4"),
                ("Brown", "#6B3A2A"),
                ("Navy Blue", "#000080"),
                ("Burgundy", "#800020"),
                ("Tan", "#D2B48C"),
                ("Cyan", "#00BCD4"),
                ("Magenta", "#FF00FF"),
            ], density=1.25, price=14.99),
            # Specialty PLA
            *_colors("PLA", [
                ("Marble Blue", "#7AA5C8"),
                ("Marble Gray", "#A0A0A0"),
                ("Glow Green", "#39FF14"),
                ("Glow Blue", "#1B03A3"),
                ("Glow Rainbow", "#CCFF00"),
                ("Carbon Fiber Black", "#333333"),
                ("Wood Light Brown", "#B19870"),
            ], nozzle_default=210, bed_default=55, price=16.99),
            # Silk PLA
            *_colors("PLA", [
                ("Silk Gold", "#D4A843"),
                ("Silk Silver", "#C0C0C0"),
                ("Silk Copper", "#B87333"),
                ("Silk Red", "#CC3333"),
                ("Silk Blue", "#336699"),
                ("Silk Green", "#339966"),
            ], nozzle_default=210, bed_default=55, price=16.99),
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Transparent", "#E0E0E0"),
                ("Translucent Red", "#CC0000"),
                ("Translucent Blue", "#0047AB"),
                ("Translucent Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Silver", "#C0C0C0"),
                ("Purple", "#7B2D8E"),
            ], nozzle_min=225, nozzle_default=240, nozzle_max=255,
               bed_default=80, price=16.99),
        ],
    },

    # ── Sunlu ─────────────────────────────────────────────────────────
    {
        "name": "Sunlu",
        "website": "https://store.sunlu.com",
        "empty_spool_weight_g": 133.0,
        "filaments": [
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Bone White", "#E3DAC9"),
                ("Cool White", "#F0F5FF"),
                ("Grey", "#808080"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Klein Blue", "#002FA7"),
                ("Cyan", "#00BCD4"),
                ("Green", "#228B22"),
                ("Olive Green", "#6B8E23"),
                ("Yellow", "#FFD700"),
                ("Vivid Yellow", "#FFE800"),
                ("Orange", "#FF6600"),
                ("Sunny Orange", "#FF9933"),
                ("Purple", "#7B2D8E"),
                ("Magenta", "#FF00FF"),
                ("Lavender", "#B57EDC"),
                ("Beige", "#D2B48C"),
                ("Coffee Brown", "#6F4E37"),
                ("Brown", "#795548"),
                ("Oak", "#B19870"),
                ("Ceramic", "#E0D5C0"),
                ("Midnight", "#191970"),
                ("Roasted Chestnut", "#986960"),
            ], nozzle_default=210, bed_default=50, price=13.99),
            # Matte PLA
            *_colors("PLA", [
                ("Matte Black", "#2A2A2A"),
                ("Matte White", "#F0F0F0"),
                ("Matte Grey", "#808080"),
                ("Matte Sakura Pink", "#FFB7C5"),
                ("Matte Matcha Green", "#8AAA79"),
                ("Matte Army Green", "#4B5320"),
                ("Matte Desert Brown", "#C4A484"),
            ], nozzle_default=210, bed_default=50, price=15.99),
            # Silk PLA
            *_colors("PLA", [
                ("Silk Gold", "#D4A843"),
                ("Silk Silver", "#C0C0C0"),
                ("Silk Copper", "#B87333"),
                ("Silk Red", "#CC3333"),
                ("Silk Blue", "#336699"),
            ], nozzle_default=210, bed_default=50, price=17.99),
            # Glow in the Dark PLA
            *_colors("PLA", [
                ("Glow Yellow", "#FFFF00"),
                ("Glow Blue", "#1B03A3"),
                ("Glow Green", "#39FF14"),
                ("Glow Red", "#FF0000"),
                ("Glow White to Blue", "#F0F0FF"),
                ("Glow White to Green", "#F0FFF0"),
            ], nozzle_default=210, bed_default=50, price=17.99),
            *_colors("PLA+", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Brown", "#795548"),
                ("Silver", "#C0C0C0"),
            ], price=15.99),
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Transparent", "#E0E0E0"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Transparent Blue", "#42A5F5"),
                ("Cyan", "#00BCD4"),
                ("Silver", "#C0C0C0"),
                ("Yellow", "#FFD700"),
            ], nozzle_default=240, bed_default=80, price=17.99),
            *_colors("ABS", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Gray", "#808080"),
                ("Orange", "#FF6600"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
            ], nozzle_default=245, bed_default=100, price=17.99),
            *_colors("ASA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Grey", "#808080"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Orange", "#FF6600"),
            ], price=19.99),
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Transparent", "#E0E0E0"),
            ], price=21.99),
        ],
    },

    # ── Eryone ────────────────────────────────────────────────────────
    {
        "name": "Eryone",
        "website": "https://eryone3d.com",
        "empty_spool_weight_g": 267.0,
        "filaments": [
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("Glossy Black", "#0A0A0A"),
                ("Carbon Black", "#222222"),
                ("Jet Black", "#050505"),
                ("White", "#FFFFFF"),
                ("Ivory White", "#FFFFF0"),
                ("Pearl White", "#F5F5F0"),
                ("Cool White", "#F0F5FF"),
                ("Milky White", "#FAFAFA"),
                ("Red", "#CC0000"),
                ("Chinese Red", "#AA381E"),
                ("Rose Red", "#FF033E"),
                ("Blue", "#0047AB"),
                ("White Jade", "#E8E8E0"),
                ("Green", "#228B22"),
                ("Apple Green", "#8DB600"),
                ("Yellow", "#FFD700"),
                ("Mango Yellow", "#FF8243"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Agate Gray", "#B5B5AA"),
                ("Signal Gray", "#96969B"),
                ("Purple", "#7B2D8E"),
                ("Dark Purple", "#4B0082"),
                ("Lavender Purple", "#B57EDC"),
                ("Silver", "#C0C0C0"),
                ("Carbon Fibre Black", "#333333"),
            ], nozzle_default=210, bed_default=55, price=17.99),
            # Silk PLA
            *_colors("PLA", [
                ("Silk Gold", "#D4A843"),
                ("Silk Silver", "#C0C0C0"),
                ("Silk Copper", "#B87333"),
                ("Silk Red", "#CC3333"),
                ("Silk Blue", "#336699"),
                ("Silk Green", "#339966"),
                ("Silk Purple", "#663399"),
            ], nozzle_default=210, bed_default=55, price=21.99),
            # Matte PLA
            *_colors("PLA", [
                ("Matte Black", "#2A2A2A"),
                ("Matte White", "#F0F0F0"),
                ("Matte Grey", "#808080"),
                ("Matte Navy", "#003366"),
                ("Matte Olive", "#6B8E23"),
            ], nozzle_default=210, bed_default=55, price=19.99),
            # Galaxy / Marble PLA
            *_colors("PLA", [
                ("Galaxy Black", "#1A1A2E"),
                ("Galaxy Purple", "#2D1B69"),
                ("Galaxy Blue", "#1A1A4E"),
                ("Marble White", "#F0EDE0"),
                ("Wood Light Brown", "#B19870"),
                ("Glow Green", "#39FF14"),
                ("Glow Blue", "#1B03A3"),
                ("Rainbow", "#FF6600"),
            ], nozzle_default=210, bed_default=55, price=21.99),
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Transparent", "#E0E0E0"),
                ("Transparent Red", "#CC0000"),
                ("Transparent Blue", "#42A5F5"),
                ("Carbon Fiber", "#333333"),
            ], nozzle_default=240, bed_default=80, price=19.99),
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Transparent", "#E0E0E0"),
            ], price=24.99),
        ],
    },

    # ── Tinmorry ──────────────────────────────────────────────────────
    {
        "name": "Tinmorry",
        "website": "https://tinmorry.com",
        "empty_spool_weight_g": 150.0,
        "filaments": [
            # PLA Standard
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("Cold White", "#F0F5FF"),
                ("Grey", "#808080"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Sky Blue", "#87CEEB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Light Brown", "#C4A484"),
                ("Transparent", "#E0E0E0"),
                ("Purple", "#7B2D8E"),
                ("Pink", "#FF69B4"),
                ("Dark Green", "#006400"),
                ("Mint Green", "#98FF98"),
                ("White", "#FFFFFF"),
                ("Warm White", "#FDF5E6"),
                ("Beige", "#CCA897"),
                ("Dark Grey", "#4A4A4A"),
            ], nozzle_default=210, bed_default=55, price=14.99),
            # Matte PLA
            *_colors("PLA", [
                ("Matte Black", "#2A2A2A"),
                ("Matte White", "#F0F0F0"),
                ("Matte Brown", "#795548"),
                ("Matte Grey", "#808080"),
                ("Matte Red", "#CC0000"),
                ("Matte Blue", "#0047AB"),
                ("Matte Green", "#228B22"),
                ("Matte Orange", "#FF6600"),
                ("Matte Yellow", "#FFD700"),
                ("Matte Pink", "#FF69B4"),
                ("Matte Purple", "#7B2D8E"),
                ("Matte Olive Green", "#6B8E23"),
                ("Matte Teal", "#008080"),
                ("Matte Cream", "#FFFDD0"),
                ("Matte Light Grey", "#C0C0C0"),
            ], nozzle_default=210, bed_default=55, price=16.99),
            # Silk PLA
            *_colors("PLA", [
                ("Silk Gold", "#D4A843"),
                ("Silk Silver", "#C0C0C0"),
                ("Silk Copper", "#B87333"),
                ("Silk Red", "#CC3333"),
                ("Silk Blue", "#336699"),
                ("Silk Bronze", "#CD7F32"),
                ("Silk Green", "#339966"),
                ("Silk Purple", "#7B2D8E"),
                ("Silk Rose Gold", "#B76E79"),
                ("Silk Champagne", "#F7E7CE"),
            ], nozzle_default=210, bed_default=55, price=17.99),
            # PLA-CF
            *_colors("PLA", [
                ("CF Black", "#333333"),
                ("CF Carbon Blue", "#2C3E50"),
                ("CF Purple Grey", "#8E7CC3"),
                ("CF Cool Grey", "#95A5A6"),
                ("CF Brick Red", "#8B2500"),
                ("CF Light Brown", "#C4A484"),
                ("CF Earth Yellow", "#DAA520"),
                ("CF Grey Green", "#5F7161"),
            ], nozzle_default=215, bed_default=55, price=21.99),
            # PETG-ECO
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("Cold White", "#F0F5FF"),
                ("Grey", "#808080"),
                ("Red", "#CC0000"),
                ("Klein Blue", "#002FA7"),
                ("Bright Yellow", "#FFD700"),
                ("Mint Green", "#98FF98"),
                ("Sky Blue", "#87CEEB"),
                ("Orange", "#FF6600"),
                ("Transparent", "#E0E0E0"),
                ("Green", "#228B22"),
                ("Purple", "#7B2D8E"),
                ("Dark Grey", "#4A4A4A"),
                ("Pink", "#FF69B4"),
                ("Light Blue", "#72AECB"),
                ("Brown", "#795548"),
                ("White", "#FFFFFF"),
                ("Warm White", "#FDF5E6"),
                ("Dark Blue", "#003366"),
                ("Olive Green", "#6B8E23"),
                ("Gold", "#CFB53B"),
                ("Beige", "#CCA897"),
                ("Teal", "#008080"),
                ("Light Green", "#BBD39B"),
                ("Cyan", "#00BFFF"),
                ("Dark Green", "#006400"),
                ("Natural", "#F0EDE0"),
                ("Dark Red", "#8B0000"),
                ("Amber", "#FFBF00"),
                ("Rose", "#FF007F"),
                ("Transparent Blue", "#42A5F5"),
                ("Transparent Green", "#66BB6A"),
            ], nozzle_default=240, bed_default=80, price=16.99),
            # Metallic PETG
            *_colors("PETG", [
                ("Metallic Silver", "#B0B0B0"),
                ("Metallic Space Grey", "#4A4A4A"),
                ("Metallic Champagne Gold", "#D4A843"),
                ("Metallic Bronze", "#CD7F32"),
                ("Metallic Copper", "#B87333"),
                ("Metallic Iron Grey", "#5A5A5A"),
                ("Metallic Midnight Blue", "#003366"),
            ], nozzle_default=240, bed_default=80, price=19.99),
            # CF PETG
            *_colors("PETG", [
                ("CF Black", "#333333"),
                ("CF Carbon Blue", "#2C3E50"),
                ("CF Marble Grey", "#A0A0A0"),
                ("CF Dark Grey", "#4A4A4A"),
                ("CF Brown", "#5C3317"),
            ], nozzle_default=240, bed_default=80, price=22.99),
            # GF PETG
            *_colors("PETG", [
                ("GF Frosted Black", "#2A2A2A"),
                ("GF Frosted White", "#F0F0F0"),
                ("GF Frosted Grey", "#808080"),
                ("GF Frosted Red", "#CC0000"),
                ("GF Frosted Blue", "#0047AB"),
                ("GF Frosted Green", "#228B22"),
                ("GF Frosted Yellow", "#FFD700"),
                ("GF Frosted Orange", "#FF6600"),
                ("GF Frosted Dark Grey", "#4A4A4A"),
                ("GF Frosted Purple", "#7B2D8E"),
                ("GF Frosted Pink", "#FF69B4"),
                ("GF Frosted Teal", "#008080"),
                ("GF Frosted Brown", "#795548"),
                ("GF Frosted Natural", "#F0EDE0"),
                ("GF Frosted Light Blue", "#72AECB"),
                ("GF Frosted Dark Blue", "#003366"),
                ("GF Frosted Olive", "#6B8E23"),
                ("GF Frosted Beige", "#CCA897"),
                ("GF Frosted Silver", "#C0C0C0"),
            ], nozzle_default=240, bed_default=80, price=22.99),
            # TPU 95A
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("Grey", "#808080"),
                ("Light Grey", "#C0C0C0"),
                ("Metallic Silver", "#B0B0B0"),
                ("Red", "#CC0000"),
                ("Rose Red", "#FF033E"),
                ("Pink", "#FF69B4"),
                ("Pale Pink", "#FFD1DC"),
                ("Space Grey", "#4A4A4A"),
                ("Traffic Yellow", "#FFD700"),
                ("Fire Safety Orange", "#FF6600"),
                ("Emerald Green", "#50C878"),
                ("Neon Blue", "#4D4DFF"),
                ("Neon Green", "#39FF14"),
                ("Neon Purple", "#B026FF"),
                ("Neon Yellow", "#FFFF00"),
                ("Neon Red", "#FF0000"),
                ("Fluorescent Blue", "#1B03A3"),
                ("Fluorescent Green", "#39FF14"),
                ("Fluorescent Purple", "#B026FF"),
                ("Fluorescent Yellow", "#CCFF00"),
                ("Fluorescent Rose Red", "#FF007F"),
                ("Transparent Clear", "#E0E0E0"),
                ("Transparent Blue", "#42A5F5"),
                ("Transparent Emerald Green", "#50C878"),
                ("Transparent Grey", "#999999"),
            ], price=18.99),
            # ABS
            *_colors("ABS", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Grey", "#808080"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Dark Grey", "#4A4A4A"),
            ], nozzle_default=245, bed_default=100, price=16.99),
            # ASA
            *_colors("ASA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Grey", "#808080"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
            ], price=19.99),
        ],
    },

    # ── Fiberlogy ─────────────────────────────────────────────────────
    # Polish manufacturer, 850g spools, no official hex — approximated from color names
    {
        "name": "Fiberlogy",
        "website": "https://fiberlogy.com",
        "empty_spool_weight_g": 292.0,
        "filaments": [
            # Easy PLA (standard colors)
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("Graphite", "#3A3A3A"),
                ("Gray", "#808080"),
                ("White", "#FFFFFF"),
                ("Lithophane White", "#FAFAFA"),
                ("Beige", "#D2B48C"),
                ("Brown", "#6B3A2A"),
                ("Burgundy", "#800020"),
                ("Red", "#CC0000"),
                ("Red Orange", "#FF4500"),
                ("Orange", "#FF6600"),
                ("Yellow", "#FFD700"),
                ("Light Green", "#90EE90"),
                ("Green", "#228B22"),
                ("Irish Green", "#009A44"),
                ("Cyan", "#00BCD4"),
                ("Blue", "#0047AB"),
                ("True Blue", "#0066FF"),
                ("Navy Blue", "#003366"),
                ("Magenta", "#FF00FF"),
                ("Pink", "#FF69B4"),
                ("Candy", "#FF1493"),
                ("Pastel Blue", "#AEC6CF"),
                ("Pastel Lilac", "#C8A2C8"),
                ("Pastel Mint", "#98FF98"),
                ("Pastel Pink", "#FFD1DC"),
                ("Pastel Yellow", "#FFFACD"),
                ("Neon Green", "#39FF14"),
                ("Neon Orange", "#FF6700"),
                ("Neon Yellow", "#FFFF00"),
                ("Skin Tone 1", "#FFE0BD"),
                ("Skin Tone 2", "#D4A76A"),
                ("Skin Tone 3", "#8D5524"),
                # Special / premium
                ("Onyx", "#353839"),
                ("Midnight Sky", "#191970"),
                ("Granite", "#676767"),
                ("Brick", "#CB4154"),
                ("Ruby Red", "#9B111E"),
                ("Spectra Blue", "#2E5090"),
                ("Aurora", "#78FFD6"),
                ("Alien Green", "#7FFF00"),
                ("Onyx Gold", "#554D36"),
                ("Sandstone", "#786D5F"),
                ("Inox", "#B0B0B0"),
                ("Vertigo", "#4A4A60"),
                ("True Gold", "#D4A843"),
                ("Old Gold", "#CFB53B"),
            ], nozzle_default=215, nozzle_min=200, nozzle_max=240, bed_default=60, net_weight_g=850.0, price=27.97),
            # Impact PLA (tougher)
            *_colors("PLA", [
                ("Impact Black", "#1A1A1A"),
                ("Impact Graphite", "#3A3A3A"),
                ("Impact Gray", "#808080"),
                ("Impact White", "#FFFFFF"),
                ("Impact Red", "#CC0000"),
                ("Impact Orange", "#FF6600"),
                ("Impact Yellow", "#FFD700"),
                ("Impact Blue", "#0047AB"),
                ("Impact Light Green", "#90EE90"),
                ("Impact Army Green", "#4B5320"),
                ("Impact Khaki", "#C3B091"),
                ("Impact Olive Green", "#6B8E23"),
                ("Impact Onyx", "#353839"),
                ("Impact Vertigo", "#4A4A60"),
            ], nozzle_default=230, nozzle_min=220, nozzle_max=245, bed_default=60, net_weight_g=850.0, price=27.97),
            # Matte PLA
            *_colors("PLA", [
                ("Matte Black", "#2A2A2A"),
                ("Matte Graphite", "#3A3A3A"),
                ("Matte Gray", "#808080"),
                ("Matte White", "#F0F0F0"),
                ("Matte Beige", "#D2B48C"),
                ("Matte Red", "#CC0000"),
                ("Matte Blue", "#0047AB"),
                ("Matte Pastel Blue", "#AEC6CF"),
                ("Matte Pastel Lilac", "#C8A2C8"),
                ("Matte Pastel Mint", "#98FF98"),
                ("Matte Pastel Pink", "#FFD1DC"),
                ("Matte Pastel Yellow", "#FFFACD"),
                ("Matte Skin Tone 1", "#FFE0BD"),
                ("Matte Skin Tone 2", "#D4A76A"),
                ("Matte Skin Tone 3", "#8D5524"),
            ], nozzle_default=215, nozzle_min=200, nozzle_max=230, bed_default=60, net_weight_g=850.0, price=29.97),
            # Easy PETG
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("Graphite", "#3A3A3A"),
                ("Gray", "#808080"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Scarlet", "#FF2400"),
                ("Orange", "#FF6600"),
                ("Yellow", "#FFD700"),
                ("Blue", "#0047AB"),
                ("Silver", "#C0C0C0"),
                ("Onyx", "#353839"),
                ("Vertigo", "#4A4A60"),
                ("Pastel Blue", "#AEC6CF"),
                ("Pastel Lilac", "#C8A2C8"),
                ("Pastel Mint", "#98FF98"),
                ("Pastel Pink", "#FFD1DC"),
                ("Pastel Yellow", "#FFFACD"),
                ("Pure Transparent", "#E0E0E0"),
                ("Burgundy Transparent", "#80002080"),
                ("Light Green Transparent", "#90EE9080"),
                ("Bottle Green Transparent", "#006A4E80"),
                ("Navy Blue Transparent", "#00336680"),
                ("Orange Transparent", "#FF660080"),
            ], nozzle_default=240, nozzle_min=220, nozzle_max=250, bed_default=90, net_weight_g=850.0, price=29.97),
            # ABS
            *_colors("ABS", [
                ("Black", "#1A1A1A"),
                ("Graphite", "#3A3A3A"),
                ("Gray", "#808080"),
                ("White", "#FFFFFF"),
                ("Beige", "#D2B48C"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Yellow", "#FFD700"),
                ("Light Green", "#90EE90"),
                ("Inox", "#B0B0B0"),
                ("Onyx", "#353839"),
                ("Vertigo", "#4A4A60"),
            ], nozzle_default=255, nozzle_min=250, nozzle_max=265, bed_default=100, bed_min=90, bed_max=110, net_weight_g=850.0, price=32.99),
            # FiberFlex 40D (TPU)
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("Graphite", "#3A3A3A"),
                ("Gray", "#808080"),
                ("White", "#FFFFFF"),
                ("Beige", "#D2B48C"),
                ("Brown", "#6B3A2A"),
                ("Red", "#CC0000"),
                ("Orange", "#FF6600"),
                ("Yellow", "#FFD700"),
                ("Neon Yellow", "#FFFF00"),
                ("Light Green", "#90EE90"),
                ("Green", "#228B22"),
                ("Blue", "#0047AB"),
                ("Navy Blue", "#003366"),
                ("Pink", "#FF69B4"),
                ("Purple", "#7B2D8E"),
                ("Burgundy", "#800020"),
                ("Skin Tone 1", "#FFE0BD"),
                ("Skin Tone 2", "#D4A76A"),
                ("Skin Tone 3", "#8D5524"),
                ("Vertigo", "#4A4A60"),
            ], nozzle_default=210, nozzle_min=200, nozzle_max=220, bed_default=70, max_speed=45, net_weight_g=850.0, price=52.00),
        ],
    },

    # ── Amazon Basics ─────────────────────────────────────────────────
    {
        "name": "Amazon Basics",
        "website": "https://www.amazon.com",
        "empty_spool_weight_g": 230.0,
        "filaments": [
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Dark Gray", "#4A4A4A"),
                ("Silver", "#C0C0C0"),
                ("Purple", "#7B2D8E"),
                ("Pink", "#FF69B4"),
                ("Dark Blue", "#003366"),
                ("Dark Green", "#006400"),
                ("Neon Green", "#39FF14"),
                ("Brown", "#6B3A2A"),
                ("Transparent", "#E0E0E0"),
            ], nozzle_default=210, bed_default=50, price=19.00),
            # Silk PLA
            *_colors("PLA", [
                ("Silk Blue", "#336699"),
                ("Silk Gold", "#D4A843"),
                ("Silk Silver", "#C0C0C0"),
                ("Silk Copper", "#B87333"),
                ("Silk Red", "#CC3333"),
                ("Silk Green", "#339966"),
            ], nozzle_default=210, bed_default=50, price=21.00),
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Purple", "#7B2D8E"),
                ("Gray", "#808080"),
                ("Orange", "#FF6600"),
                ("Translucent", "#E0E0E0"),
            ], nozzle_default=240, bed_default=80, price=19.99),
            *_colors("ABS", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Gray", "#808080"),
            ], nozzle_default=240, bed_default=100, price=19.99),
        ],
    },

    # ── MatterHackers Build Series ────────────────────────────────────
    {
        "name": "MatterHackers",
        "website": "https://www.matterhackers.com",
        "empty_spool_weight_g": 215.0,
        "filaments": [
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Light Blue", "#87CEEB"),
                ("Green", "#228B22"),
                ("Forest Green", "#006400"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Silver", "#C0C0C0"),
                ("Purple", "#7B2D8E"),
                ("Magenta", "#FF00FF"),
                ("Pink", "#FF69B4"),
                ("Tan", "#D2B48C"),
                ("Brown", "#6B3A2A"),
                ("Natural", "#F0EDE0"),
            ], nozzle_min=190, nozzle_default=205, nozzle_max=220,
               bed_default=50, density=1.25, price=19.31),
            # Translucent PLA
            *_colors("PLA", [
                ("Translucent Red", "#CC0000"),
                ("Translucent Blue", "#42A5F5"),
                ("Translucent Green", "#4CAF50"),
                ("Translucent Orange", "#FF9800"),
                ("Translucent Purple", "#9C27B0"),
                ("Translucent Yellow", "#FFEB3B"),
            ], nozzle_min=190, nozzle_default=205, nozzle_max=220,
               bed_default=50, density=1.25, price=22.49),
            # Silky/Magic PLA
            *_colors("PLA", [
                ("Silky Pink Blue", "#E91E63"),
                ("Silky Gold Silver", "#D4A843"),
            ], nozzle_min=190, nozzle_default=205, nozzle_max=220,
               bed_default=50, density=1.25, price=24.99),
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Silver", "#C0C0C0"),
                ("Purple", "#7B2D8E"),
                ("Clear Translucent", "#E0E0E0"),
                ("Translucent Red", "#CC0000"),
                ("Translucent Blue", "#42A5F5"),
                ("Translucent Green", "#4CAF50"),
                ("Translucent Orange", "#FF9800"),
                ("Translucent Purple", "#9C27B0"),
                ("Translucent Yellow", "#FFEB3B"),
                ("Translucent Gray", "#999999"),
            ], nozzle_min=225, nozzle_default=240, bed_default=80, price=24.00),
            *_colors("ABS", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
            ], nozzle_default=240, bed_default=100, price=24.00),
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
            ], price=39.99),
        ],
    },

    # ── Creality ──────────────────────────────────────────────────────
    {
        "name": "Creality",
        "website": "https://store.creality.com",
        "empty_spool_weight_g": 140.0,
        "filaments": [
            # Ender PLA
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Grey", "#808080"),
                ("Orange", "#FF6600"),
                ("Purple", "#7B2D8E"),
                ("Skin", "#FFCBA4"),
            ], nozzle_min=190, nozzle_default=210, bed_default=50, price=12.99),
            # Hyper PLA (high speed)
            *_colors("PLA", [
                ("Hyper Milk White", "#FFFFFF"),
                ("Hyper Dark Black", "#1A1A1A"),
                ("Hyper Space Grey", "#4A4A4A"),
                ("Hyper Rose Red", "#E91E63"),
                ("Hyper Ocean Blue", "#0277BD"),
                ("Hyper Red", "#CC0000"),
                ("Hyper Blue", "#0047AB"),
                ("Hyper Green", "#228B22"),
                ("Hyper Yellow", "#FFD700"),
                ("Hyper Orange", "#FF6600"),
                ("Hyper Brown", "#795548"),
                ("Hyper Purple", "#7B2D8E"),
                ("Hyper Pink", "#FF69B4"),
                ("Hyper Rainbow", "#FF6600"),
            ], nozzle_min=190, nozzle_default=220, bed_default=50,
               max_flow=21.0, max_speed=300, price=15.99),
            # Hyper PLA-CF
            *_colors("PLA", [
                ("Hyper CF Black", "#333333"),
            ], nozzle_min=200, nozzle_default=220, bed_default=55,
               max_flow=18.0, max_speed=250, price=19.99),
            # Hyper PETG
            *_colors("PETG", [
                ("Hyper Black", "#1A1A1A"),
                ("Hyper White", "#FFFFFF"),
                ("Hyper Grey", "#808080"),
                ("Hyper Red", "#CC0000"),
                ("Hyper Blue", "#0047AB"),
                ("Hyper Orange", "#FF6600"),
                ("Hyper Green", "#228B22"),
            ], nozzle_default=240, bed_default=80,
               max_flow=16.0, max_speed=300, price=19.99),
        ],
    },

    # ── Jayo ──────────────────────────────────────────────────────────
    {
        "name": "Jayo",
        "website": "https://www.jayo3d.com",
        "empty_spool_weight_g": 135.0,
        "filaments": [
            *_colors("PLA", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Cherry Red", "#DE3163"),
                ("Blue", "#0047AB"),
                ("Sky Blue", "#87CEEB"),
                ("Blue Grey", "#6E7F8D"),
                ("Green", "#228B22"),
                ("Grass Green", "#7CFC00"),
                ("Mint Green", "#98FF98"),
                ("Yellow", "#FFD700"),
                ("Lemon Yellow", "#FFF44F"),
                ("Orange", "#FF6600"),
                ("Sunny Orange", "#FF9933"),
                ("Gray", "#808080"),
                ("Silver", "#C0C0C0"),
                ("Purple", "#7B2D8E"),
                ("Pink", "#FF69B4"),
                ("Brown", "#6B3A2A"),
                ("Beige", "#D2B48C"),
                ("Cyan", "#00BCD4"),
                ("Fuchsia", "#FF00FF"),
                ("Transparent", "#E0E0E0"),
                ("Transparent Yellow", "#FFEB3B"),
            ], nozzle_default=210, bed_default=55, price=11.99),
            # PLA Matte
            *_colors("PLA", [
                ("Matte Black", "#2A2A2A"),
                ("Matte White", "#F0F0F0"),
                ("Matte Grey", "#808080"),
                ("Matte Red", "#CC0000"),
                ("Matte Blue", "#0047AB"),
                ("Matte Green", "#228B22"),
            ], nozzle_default=210, bed_default=55, price=13.99),
            # Silk PLA
            *_colors("PLA", [
                ("Silk Gold", "#D4A843"),
                ("Silk Silver", "#C0C0C0"),
                ("Silk Copper", "#B87333"),
                ("Silk Red", "#CC3333"),
                ("Silk Blue", "#336699"),
            ], nozzle_default=210, bed_default=55, price=15.99),
            # Specialty PLA
            *_colors("PLA", [
                ("Wood", "#B19870"),
                ("Marble", "#E0DCD0"),
                ("Glow Green", "#39FF14"),
                ("Rainbow", "#FF6600"),
            ], nozzle_default=210, bed_default=55, price=15.99),
            *_colors("PLA+", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Yellow", "#FFD700"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Silver", "#C0C0C0"),
                ("Cyan", "#00BCD4"),
            ], price=13.99),
            *_colors("PETG", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Green", "#228B22"),
                ("Orange", "#FF6600"),
                ("Gray", "#808080"),
                ("Transparent", "#E0E0E0"),
                ("Yellow", "#FFD700"),
                ("Silver", "#C0C0C0"),
            ], nozzle_default=240, bed_default=80, price=15.99),
            *_colors("ABS", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Gray", "#808080"),
                ("Orange", "#FF6600"),
            ], nozzle_default=245, bed_default=100, price=16.99),
            *_colors("TPU", [
                ("Black", "#1A1A1A"),
                ("White", "#FFFFFF"),
                ("Red", "#CC0000"),
                ("Blue", "#0047AB"),
                ("Transparent", "#E0E0E0"),
            ], price=18.99),
        ],
    },
]
