"""G-code metadata parser — extract per-tool filament usage from PrusaSlicer output."""

from __future__ import annotations

import re


def parse_filament_usage_g(gcode_text: str) -> list[float]:
    """Extract per-tool filament usage in grams from G-code comments.

    PrusaSlicer format:  ; filament used [g] = 13.49, 5.67
    Returns list of floats (one per tool).
    """
    for line in gcode_text.split("\n"):
        m = re.match(r";\s*filament used \[g\]\s*=\s*(.+)", line)
        if m:
            parts = m.group(1).split(",")
            return [float(p.strip()) for p in parts if p.strip()]
    return []


def parse_filament_colors(gcode_text: str) -> list[str]:
    """Extract per-tool filament colors from G-code comments.

    PrusaSlicer format:  ; filament_colour = #FF0000;#00FF00
    Returns list of hex strings.
    """
    for line in gcode_text.split("\n"):
        m = re.match(r";\s*filament_colour\s*=\s*(.+)", line)
        if m:
            return [c.strip() for c in m.group(1).split(";") if c.strip()]
    return []


def parse_filament_types(gcode_text: str) -> list[str]:
    """Extract per-tool filament material types from G-code comments.

    PrusaSlicer format:  ; filament_type = PLA;PETG
    Returns list of material strings.
    """
    for line in gcode_text.split("\n"):
        m = re.match(r";\s*filament_type\s*=\s*(.+)", line)
        if m:
            return [t.strip() for t in m.group(1).split(";") if t.strip()]
    return []


def parse_project_name(gcode_text: str) -> str:
    """Try to extract project/model name from G-code.

    Looks for:  ; generated by PrusaSlicer ...
    Or the filename in the header comments.
    """
    for line in gcode_text.split("\n"):
        # Look for original filename
        m = re.match(r";\s*original_filename\s*=\s*(.+)", line)
        if m:
            name = m.group(1).strip()
            # Remove .gcode extension
            if name.lower().endswith(".gcode"):
                name = name[:-6]
            return name
    return "Unknown"
