"""PrusaSlicer .ini filament profile generator."""

from __future__ import annotations

from app.db.models import Filament, Spool


def generate_prusaslicer_profile(filament: Filament, vendor_name: str) -> str:
    """Generate a PrusaSlicer filament profile .ini file content."""
    nozzle = filament.nozzle_temp_default or 210
    bed = filament.bed_temp_default or 60
    density = filament.density_g_cm3 or 1.24
    diameter = filament.diameter_mm or 1.75
    color = filament.color_hex or "#FFFFFF"

    # Ensure color has # prefix
    if not color.startswith("#"):
        color = f"#{color}"

    price_per_kg = 0.0
    if filament.price:
        if filament.price_unit == "per_kg":
            price_per_kg = filament.price
        elif filament.net_weight_g and filament.net_weight_g > 0:
            price_per_kg = filament.price / (filament.net_weight_g / 1000.0)

    spool_weight = filament.spool_weight_g or 0

    lines = [
        f"# Generated by Spool Station",
        f"# {vendor_name} - {filament.name}",
        f"",
        f"filament_settings_id = {vendor_name} {filament.name}",
        f"filament_type = {filament.material}",
        f"filament_vendor = {vendor_name}",
        f"filament_colour = {color}",
        f"filament_diameter = {diameter}",
        f"filament_density = {density}",
        f"filament_cost = {price_per_kg:.2f}",
        f"filament_spool_weight = {spool_weight:.0f}",
        f"temperature = {nozzle}",
        f"first_layer_temperature = {nozzle + 5}",
        f"bed_temperature = {bed}",
        f"first_layer_bed_temperature = {bed + 5}",
        f"filament_notes = Generated by Spool Station\\n{vendor_name} {filament.name}",
    ]

    if filament.max_volumetric_flow:
        lines.append(f"filament_max_volumetric_speed = {filament.max_volumetric_flow}")

    return "\n".join(lines) + "\n"


def generate_spool_profile(spool: Spool, filament: Filament, vendor_name: str) -> str:
    """Generate a per-spool PrusaSlicer profile with correct color and remaining weight.

    Profile name format: '{Vendor} {Material} {Color} — {remaining}g'
    This gives the user an at-a-glance view of remaining filament in the slicer.
    """
    nozzle = filament.nozzle_temp_default or 210
    bed = filament.bed_temp_default or 60
    density = filament.density_g_cm3 or 1.24
    diameter = filament.diameter_mm or 1.75
    color = filament.color_hex or "#FFFFFF"

    if not color.startswith("#"):
        color = f"#{color}"

    remaining = spool.remaining_weight_g
    color_name = filament.color_name or filament.name

    price_per_kg = 0.0
    if filament.price:
        if filament.price_unit == "per_kg":
            price_per_kg = filament.price
        elif filament.net_weight_g and filament.net_weight_g > 0:
            price_per_kg = filament.price / (filament.net_weight_g / 1000.0)

    spool_weight = filament.spool_weight_g or 0
    profile_name = f"{vendor_name} {filament.material} {color_name} — {remaining:.0f}g"

    lines = [
        f"# Generated by Spool Station (per-spool profile)",
        f"# {vendor_name} - {filament.name} (Spool #{spool.id})",
        f"",
        f"filament_settings_id = {profile_name}",
        f"filament_type = {filament.material}",
        f"filament_vendor = {vendor_name}",
        f"filament_colour = {color}",
        f"filament_diameter = {diameter}",
        f"filament_density = {density}",
        f"filament_cost = {price_per_kg:.2f}",
        f"filament_spool_weight = {spool_weight:.0f}",
        f"temperature = {nozzle}",
        f"first_layer_temperature = {nozzle + 5}",
        f"bed_temperature = {bed}",
        f"first_layer_bed_temperature = {bed + 5}",
        f"filament_notes = Spool Station Spool #{spool.id}\\n"
        f"{vendor_name} {filament.name}\\n"
        f"Remaining: {remaining:.0f}g",
    ]

    if filament.max_volumetric_flow:
        lines.append(f"filament_max_volumetric_speed = {filament.max_volumetric_flow}")

    return "\n".join(lines) + "\n"
